import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/legal-page";

export const metadata: Metadata = { title: "Política de Privacidad", description: "Cómo MultiLinks recopila, utiliza y protege los datos personales." };

const sections: LegalSection[] = [
  { title: "Información que recopilamos", paragraphs: ["Recopilamos la información necesaria para crear cuentas, publicar perfiles, brindar soporte, proteger el servicio y medir su funcionamiento."], bullets: ["Correo electrónico, identificador de cuenta y datos básicos de autenticación.", "Nombre público, username, biografía, foto, preferencias visuales y enlaces que decidas publicar.", "Visitas y clics agregados, fecha y datos técnicos mínimos necesarios para seguridad.", "Reportes, solicitudes de soporte y acciones administrativas relacionadas."] },
  { title: "Cómo utilizamos los datos", paragraphs: ["Utilizamos los datos para operar la plataforma, autenticar usuarios, mostrar páginas públicas, guardar cambios, ofrecer estadísticas, responder solicitudes y prevenir abuso."], bullets: ["Proporcionar y mejorar las funciones de MultiLinks.", "Enviar confirmaciones de cuenta, enlaces de acceso y comunicaciones de seguridad.", "Detectar fraude, limitar solicitudes abusivas y aplicar nuestras normas.", "Cumplir obligaciones legales y proteger derechos de usuarios o terceros."] },
  { title: "Información pública", paragraphs: ["El nombre, username, biografía, foto y enlaces de un perfil publicado son accesibles públicamente y pueden ser indexados o compartidos por terceros. No publiques información que quieras mantener privada."] },
  { title: "Proveedores", paragraphs: ["Utilizamos proveedores que procesan datos para prestar el servicio. Actualmente incluyen Supabase para autenticación, base de datos y almacenamiento, y Vercel para alojamiento y distribución de la aplicación. Estos proveedores aplican sus propias medidas y condiciones de privacidad." ] },
  { title: "Cookies y sesiones", paragraphs: ["MultiLinks utiliza cookies o mecanismos equivalentes necesarios para mantener la sesión, proteger rutas privadas y recordar el acceso. No vendemos información personal ni utilizamos cookies publicitarias propias en esta versión del servicio."] },
  { title: "Analítica y límites de seguridad", paragraphs: ["Registramos visitas y clics agregados para ofrecer estadísticas. Para prevenir abuso generamos huellas irreversibles mediante SHA-256 a partir de datos técnicos como IP, correo o contexto de la solicitud. Las tablas de límites no almacenan esos valores originales."] },
  { title: "Conservación", paragraphs: ["Conservamos los datos mientras la cuenta esté activa o mientras sean necesarios para prestar el servicio. Reportes, auditorías y registros de seguridad pueden conservarse durante un periodo adicional razonable para prevenir abuso, resolver disputas o cumplir obligaciones legales."] },
  { title: "Tus opciones y derechos", paragraphs: ["Puedes editar la información pública y tus enlaces desde el dashboard. También puedes solicitar acceso, corrección o eliminación de datos mediante el Centro de Ayuda. Verificaremos la identidad antes de atender solicitudes que afecten una cuenta."], bullets: ["Modificar o despublicar tu perfil.", "Solicitar corrección o eliminación de información personal.", "Consultar sobre un reporte o suspensión.", "Cerrar sesión y restablecer tus credenciales."] },
  { title: "Seguridad", paragraphs: ["Aplicamos control de acceso, RLS en la base de datos, separación de credenciales administrativas, validación de entradas, límites de frecuencia y registro de acciones de moderación. Ningún sistema es infalible, por lo que recomendamos utilizar una contraseña única y proteger tu correo."] },
  { title: "Menores y cambios", paragraphs: ["MultiLinks no está diseñado para recopilar deliberadamente datos de menores sin autorización aplicable. Si crees que existe información de un menor publicada indebidamente, repórtala. Podemos actualizar esta política y mostraremos la nueva fecha de vigencia." ] },
  { title: "Contacto", paragraphs: ["Para preguntas de privacidad, solicitudes relacionadas con tus datos o reportes de seguridad, utiliza el Centro de Ayuda o escribe a axccolas@gmail.com."] },
];

export default function PrivacyPage() { return <LegalPage eyebrow="TU INFORMACIÓN" title="Política de Privacidad" intro="Explicamos qué información utiliza MultiLinks, por qué la necesitamos y qué control tienes sobre ella." sections={sections}/>; }
