import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/legal-page";

export const metadata: Metadata = { title: "Política de Privacidad", description: "Cómo MultiLinks recopila, utiliza y protege los datos personales." };

const sections: LegalSection[] = [
  { title: "Información que recopilamos", paragraphs: ["Recopilamos la información necesaria para crear cuentas, publicar perfiles, brindar soporte, proteger el servicio y medir su funcionamiento."], bullets: ["Correo electrónico, identificador de cuenta y datos básicos de autenticación.", "Nombre público, username, biografía, foto, preferencias visuales y enlaces que decidas publicar.", "Visitas y clics agregados, fecha y datos técnicos mínimos necesarios para seguridad.", "Reportes, solicitudes de soporte y acciones administrativas relacionadas."] },
  { title: "Cómo utilizamos los datos", paragraphs: ["Utilizamos los datos para operar la plataforma, autenticar usuarios, mostrar páginas públicas, guardar cambios, ofrecer estadísticas, responder solicitudes y prevenir abuso."], bullets: ["Proporcionar y mejorar las funciones de MultiLinks.", "Enviar confirmaciones de cuenta, enlaces de acceso y comunicaciones de seguridad.", "Detectar fraude, limitar solicitudes abusivas y aplicar nuestras normas.", "Cumplir obligaciones legales y proteger derechos de usuarios o terceros."] },
  { title: "Información pública", paragraphs: ["El nombre, username, biografía, foto y enlaces de un perfil publicado son accesibles públicamente y pueden ser indexados o compartidos por terceros. No publiques información que quieras mantener privada."] },
  { title: "Proveedores y pagos", paragraphs: ["Supabase actúa como procesador de datos para la autenticación, la base de datos y el almacenamiento de MultiLinks. Vercel aloja y distribuye la aplicación.", "Los pagos y las suscripciones son procesados por Lemon Squeezy y sus métodos compatibles, incluido PayPal. MultiLinks no recibe ni almacena números completos de tarjeta, códigos de seguridad ni credenciales de pago. Conservamos únicamente los identificadores y el estado de la suscripción necesarios para habilitar las funciones contratadas."] },
  { title: "Cookies y sesiones", paragraphs: ["MultiLinks utiliza cookies o mecanismos equivalentes necesarios para mantener la sesión, proteger rutas privadas y recordar el acceso. No vendemos información personal ni utilizamos cookies publicitarias propias en esta versión del servicio."] },
  { title: "Analítica y límites de seguridad", paragraphs: ["Registramos visitas y clics agregados para ofrecer estadísticas. Para prevenir abuso generamos huellas irreversibles mediante SHA-256 a partir de datos técnicos como IP, correo o contexto de la solicitud. Las tablas de límites no almacenan esos valores originales."] },
  { title: "Conservación", paragraphs: ["Conservamos los datos mientras la cuenta esté activa o mientras sean necesarios para prestar el servicio. Al solicitar la eliminación de una cuenta, retiraremos o anonimizaremos sus datos personales, salvo aquellos que debamos conservar temporalmente por obligaciones legales, contables, prevención de fraude o resolución de disputas.", "Reportes, auditorías, registros de seguridad y datos agregados pueden conservarse durante un periodo adicional razonable cuando ya no identifiquen directamente al usuario o cuando exista una justificación legal para su conservación."] },
  { title: "Tus opciones y derechos", paragraphs: ["Puedes editar la información pública y tus enlaces desde el dashboard. Para solicitar una copia, corrección o eliminación de tus datos, utiliza el formulario de soporte del Centro de Ayuda o escribe al contacto de privacidad. Verificaremos la identidad antes de atender solicitudes que afecten una cuenta."], bullets: ["Acceder a los datos asociados con tu cuenta.", "Modificar o despublicar tu perfil.", "Solicitar corrección o eliminación de información personal.", "Consultar sobre un reporte o suspensión.", "Cerrar sesión y restablecer tus credenciales."] },
  { title: "Seguridad", paragraphs: ["Aplicamos control de acceso, RLS en la base de datos, separación de credenciales administrativas, validación de entradas, límites de frecuencia y registro de acciones de moderación. Ningún sistema es infalible, por lo que recomendamos utilizar una contraseña única y proteger tu correo."] },
  { title: "Menores y cambios", paragraphs: ["MultiLinks no está diseñado para recopilar deliberadamente datos de menores sin autorización aplicable. Si crees que existe información de un menor publicada indebidamente, repórtala. Podemos actualizar esta política y mostraremos la nueva fecha de vigencia." ] },
  { title: "Contacto de privacidad", paragraphs: ["Para ejercer tus derechos, realizar preguntas de privacidad o reportar un problema de seguridad, utiliza el Centro de Ayuda o escribe a axccolas@gmail.com indicando el correo asociado a tu cuenta y el tipo de solicitud. No incluyas contraseñas ni datos completos de pago."] },
];

export default function PrivacyPage() { return <LegalPage eyebrow="TU INFORMACIÓN" title="Política de Privacidad" intro="Explicamos qué información utiliza MultiLinks, por qué la necesitamos y qué control tienes sobre ella." sections={sections}/>; }
