import Link from "next/link";
import { ArrowLeft, Scale } from "lucide-react";
import { Logo } from "@/components/logo";

export type LegalSection = { title: string; paragraphs: string[]; bullets?: string[] };

export function LegalPage({ eyebrow, title, intro, sections }: { eyebrow: string; title: string; intro: string; sections: LegalSection[] }) {
  return <main className="min-h-screen bg-cream px-5 py-8 text-ink sm:py-12"><div className="mx-auto max-w-4xl"><header className="flex items-center justify-between gap-4"><Logo/><Link href="/" className="inline-flex items-center gap-2 border-2 border-ink bg-white px-3 py-2 text-sm font-black shadow-[3px_3px_0_#151515]"><ArrowLeft size={16}/> Inicio</Link></header><section className="mt-12 animate-fade-up"><span className="inline-flex rotate-[-2deg] items-center gap-2 border-2 border-ink bg-lime px-4 py-2 font-display text-xs font-black shadow-hard"><Scale size={17}/> {eyebrow}</span><h1 className="mt-7 font-display text-4xl font-black leading-tight tracking-[-.04em] sm:text-6xl">{title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-black/60">{intro}</p><p className="mt-4 font-display text-[10px] font-black uppercase tracking-[.13em] text-grape-dark">Vigente desde el 9 de agosto de 2026</p></section><div className="mt-12 space-y-6">{sections.map((section, index) => <section key={section.title} className="animate-fade-up border-[3px] border-ink bg-white p-6 shadow-hard sm:p-8" style={{ animationDelay: `${index * 50}ms` }}><h2 className="font-display text-lg font-black"><span className="mr-3 text-grape-dark">{String(index + 1).padStart(2, "0")}</span>{section.title}</h2><div className="mt-5 space-y-4 leading-7 text-black/65">{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.bullets ? <ul className="list-disc space-y-2 pl-6">{section.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul> : null}</div></section>)}</div><footer className="mt-10 flex flex-wrap items-center justify-between gap-4 border-t-[3px] border-ink py-8 text-sm font-bold"><p>¿Tienes preguntas sobre este documento?</p><Link href="/ayuda" className="border-2 border-ink bg-grape px-4 py-2 text-white shadow-[3px_3px_0_#151515]">Contactar soporte</Link></footer></div></main>;
}
