import { Mail, MessageCircle } from "lucide-react";
import { updateSupportRequest } from "@/app/admin/actions";
import { SubmitButton } from "@/components/admin/submit-button";

export type SupportRequestRow = { id: string; email: string; subject: string; message: string; status: string; created_at: string };

export function AdminSupport({ requests }: { requests: SupportRequestRow[] }) {
  return <section id="soporte" className="mt-8 overflow-hidden rounded-[2rem] border border-white/15 bg-[#101318]/95 text-white shadow-[0_28px_90px_rgba(0,0,0,.35)]">
    <div className="flex items-center justify-between gap-4 border-b border-white/10 p-5"><div><p className="font-display text-xs font-black uppercase tracking-[.14em] text-lime">Soporte</p><h2 className="mt-1 font-display text-xl font-black">Mensajes abiertos</h2></div><span className="grid h-12 w-12 place-items-center rounded-xl border border-lime/25 bg-lime/10 text-lime"><MessageCircle/></span></div>
    <div className="grid gap-4 p-5 lg:grid-cols-2">{requests.map((request) => <article key={request.id} className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="flex items-start justify-between gap-3"><div><span className="rounded-full border border-white/15 bg-white/[.05] px-2.5 py-1 text-xs font-black text-white/65">{request.status === "in_progress" ? "En proceso" : "Abierto"}</span><h3 className="mt-4 font-display text-base font-black">{request.subject}</h3></div><a href={`mailto:${request.email}`} aria-label={`Responder a ${request.email}`} className="rounded-xl border border-grape/35 bg-grape/15 p-2 text-grape transition hover:border-grape/70 motion-reduce:transition-none"><Mail size={18}/></a></div><p className="mt-2 break-all text-xs font-bold text-white/35">{request.email}</p><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-white/65">{request.message}</p><p className="mt-4 text-xs font-bold text-white/30">{new Intl.DateTimeFormat("es-DO", { dateStyle: "medium", timeStyle: "short" }).format(new Date(request.created_at))}</p><div className="mt-4 flex gap-2">{request.status === "open" ? <form action={updateSupportRequest}><input type="hidden" name="requestId" value={request.id}/><input type="hidden" name="status" value="in_progress"/><SubmitButton className="rounded-xl bg-lime px-3 py-2 text-xs font-black text-ink transition hover:shadow-[0_10px_26px_rgba(201,255,88,.16)] motion-reduce:transition-none">Tomar caso</SubmitButton></form> : null}<form action={updateSupportRequest}><input type="hidden" name="requestId" value={request.id}/><input type="hidden" name="status" value="closed"/><SubmitButton className="rounded-xl border border-white/15 bg-white/[.04] px-3 py-2 text-xs font-black text-white/70 transition hover:border-white/30 hover:text-white motion-reduce:transition-none">Cerrar</SubmitButton></form></div></article>)}</div>
    {requests.length === 0 ? <p className="p-10 text-center font-display text-sm font-black text-white/45">NO HAY SOLICITUDES ABIERTAS</p> : null}
  </section>;
}
