import { Mail, MessageCircle } from "lucide-react";
import { updateSupportRequest } from "@/app/admin/actions";
import { SubmitButton } from "@/components/admin/submit-button";

export type SupportRequestRow = { id: string; email: string; subject: string; message: string; status: string; created_at: string };

export function AdminSupport({ requests }: { requests: SupportRequestRow[] }) {
  return <section id="soporte" className="mt-8 border-[3px] border-ink bg-lime shadow-hard-lg"><div className="flex items-center justify-between gap-4 border-b-[3px] border-ink p-5"><div><p className="font-display text-xs font-black uppercase tracking-[.14em] text-grape-dark">Soporte</p><h2 className="mt-1 font-display text-xl font-black">Mensajes abiertos</h2></div><span className="grid h-12 w-12 place-items-center border-2 border-ink bg-white shadow-hard"><MessageCircle/></span></div><div className="grid gap-4 p-5 lg:grid-cols-2">{requests.map((request) => <article key={request.id} className="border-[3px] border-ink bg-white p-5 shadow-hard"><div className="flex items-start justify-between gap-3"><div><span className="border-2 border-ink bg-cream px-2 py-1 text-xs font-black">{request.status === "in_progress" ? "En proceso" : "Abierto"}</span><h3 className="mt-4 font-display text-base font-black">{request.subject}</h3></div><a href={`mailto:${request.email}`} aria-label={`Responder a ${request.email}`} className="border-2 border-ink bg-grape p-2 text-white shadow-[3px_3px_0_#151515]"><Mail size={18}/></a></div><p className="mt-2 break-all text-xs font-bold text-black/45">{request.email}</p><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-black/70">{request.message}</p><p className="mt-4 text-xs font-bold text-black/40">{new Intl.DateTimeFormat("es-DO", { dateStyle: "medium", timeStyle: "short" }).format(new Date(request.created_at))}</p><div className="mt-4 flex gap-2">{request.status === "open" ? <form action={updateSupportRequest}><input type="hidden" name="requestId" value={request.id}/><input type="hidden" name="status" value="in_progress"/><SubmitButton className="border-2 border-ink bg-lime px-3 py-2 text-xs font-black shadow-[3px_3px_0_#151515]">Tomar caso</SubmitButton></form> : null}<form action={updateSupportRequest}><input type="hidden" name="requestId" value={request.id}/><input type="hidden" name="status" value="closed"/><SubmitButton className="border-2 border-ink bg-ink px-3 py-2 text-xs font-black text-white shadow-[3px_3px_0_#151515]">Cerrar</SubmitButton></form></div></article>)}</div>{requests.length === 0 ? <p className="p-10 text-center font-display text-sm font-black">NO HAY SOLICITUDES ABIERTAS</p> : null}</section>;
}
