import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import { verifyWebhookSignature, safeLemonUrl, subscriptionSnapshot, webhookSubscriptionId, BILLING_EVENTS } from '../lib/billing-webhook.ts';
import { canUseFeature, hasPremiumAccess } from '../lib/premium-access.ts';
const raw='{"meta":{"event_name":"subscription_created"}}';
const signature=createHmac('sha256','fixture-secret').update(raw).digest('hex');
assert.equal(verifyWebhookSignature(raw,signature,'fixture-secret'),true);
assert.equal(verifyWebhookSignature(raw+' ',signature,'fixture-secret'),false);
assert.equal(verifyWebhookSignature(raw,'bad','fixture-secret'),false);
assert.equal(verifyWebhookSignature(raw,signature,undefined),false);
for(const url of ['javascript:alert(1)','http://store.lemonsqueezy.com','https://lemonsqueezy.com.attacker.test','https://attacker.test/lemonsqueezy.com','https://user:password@store.lemonsqueezy.com']) assert.equal(safeLemonUrl(url),null);
assert.equal(safeLemonUrl('https://store.lemonsqueezy.com/checkout/fixture'),'https://store.lemonsqueezy.com/checkout/fixture');
const config={store:'1',monthly:'2',annual:'3',testMode:true};
const resource={type:'subscriptions',id:'11',attributes:{store_id:1,variant_id:2,customer_id:12,test_mode:true,status:'active',created_at:'2026-01-01T00:00:00Z',updated_at:'2026-01-02T00:00:00Z',renews_at:'2026-02-01T00:00:00Z',ends_at:null,urls:{customer_portal:'https://store.lemonsqueezy.com/billing'}}};
assert.equal(subscriptionSnapshot(resource,config).period_end,resource.attributes.renews_at);
assert.equal(subscriptionSnapshot({...resource,attributes:{...resource.attributes,status:'cancelled',ends_at:'2026-01-20T00:00:00Z'}},config).period_end,'2026-01-20T00:00:00Z');
for(const override of [{store_id:9},{variant_id:9},{test_mode:false},{renews_at:null}]) assert.throws(()=>subscriptionSnapshot({...resource,attributes:{...resource.attributes,...override}},config));
assert.equal(BILLING_EVENTS.has('subscription_payment_success'),true);
assert.equal(BILLING_EVENTS.has('order_created'),false);
assert.equal(webhookSubscriptionId('subscription_payment_success',{id:'999',attributes:{subscription_id:11}}),'11');
assert.equal(webhookSubscriptionId('subscription_created',{id:'11'}),'11');
assert.equal(webhookSubscriptionId('subscription_payment_success',{id:'999'}),null);
assert.equal(webhookSubscriptionId('subscription_created',{id:'invalid'}),null);
assert.equal(hasPremiumAccess(null),false);
assert.equal(canUseFeature({features:{advanced_analytics:false}},'advanced_analytics'),false);
assert.equal(canUseFeature({features:{advanced_analytics:true}},'advanced_analytics'),true);
console.log('Billing: HMAC tampering, fail-closed access, safe redirects, store/variant/test-mode validation and cancellation period passed.');
