import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const { PGlite } = await import('../.analytics-test-runtime/node_modules/@electric-sql/pglite/dist/index.js');
const db=new PGlite();
try {
await db.exec(`
create role anon;create role authenticated;create role service_role;
create schema auth;create schema storage;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.user',true),'')::uuid$$;
create table auth.users(id uuid primary key,created_at timestamptz default now());
create table public.admins(user_id uuid primary key);
create table public.plans(id text primary key,name text,price_monthly integer,features jsonb);
insert into plans values('free','Free',0,'[]'),('pro','Pro',350,'[]');
create table public.subscriptions(user_id uuid primary key references auth.users(id),plan_id text references plans(id),status text default 'active',provider_customer_id text,provider_subscription_id text unique,current_period_end timestamptz,created_at timestamptz default now(),updated_at timestamptz default now(),provider_variant_id text,billing_interval text,billing_portal_url text,pro_welcome_seen boolean default false);
create table public.profiles(id uuid primary key references auth.users(id),published boolean default true,theme text default 'lime',background_color text default '#c9ff58',cover_image text,bio text default '');
create table public.links(id uuid primary key,profile_id uuid references profiles(id),url text,active boolean default true,position integer,created_at timestamptz default now(),clicks integer default 0,plays integer default 0,title text default 'Test',provider text default 'generic',metadata jsonb default '{}',link_type text default 'standard');
create table public.link_daily_clicks(link_id uuid,day date,clicks integer,primary key(link_id,day));
create table public.link_daily_plays(link_id uuid,day date,plays integer,primary key(link_id,day));
create table public.billing_webhook_events(id text primary key,event_name text,processed_at timestamptz default now());
create table storage.objects(bucket_id text,name text);
create function storage.foldername(value text) returns text[] language sql as $$select string_to_array(value,'/')$$;
create function public.is_admin() returns boolean language sql security definer as $$select exists(select 1 from public.admins where user_id=auth.uid())$$;
create function public.profile_is_available(id uuid) returns boolean language sql security definer as $$select exists(select 1 from profiles where profiles.id=$1 and published)$$;
create function public.create_free_subscription() returns trigger language plpgsql as $$begin insert into subscriptions(user_id,plan_id) values(new.id,'free');return new;end$$;
create trigger subscription_on_signup after insert on auth.users for each row execute function public.create_free_subscription();
alter table subscriptions enable row level security;
grant select on subscriptions to authenticated;
create policy owner_subscription on subscriptions for select using(user_id=auth.uid());
alter table profiles enable row level security;
alter table links enable row level security;
grant select,insert,update on profiles,links to authenticated;
grant select on profiles,links to anon;
create policy owner_profiles on profiles for all using(id=auth.uid()) with check(id=auth.uid());
create policy owner_links on links for all using(profile_id=auth.uid()) with check(profile_id=auth.uid());
`);
const old='00000000-0000-0000-0000-000000000001';const young='00000000-0000-0000-0000-000000000002';const fresh='00000000-0000-0000-0000-000000000003';
await db.query("insert into auth.users(id,created_at) values($1,now()-interval '80 days'),($2,now()-interval '3 days')",[old,young]);
const migration=await readFile(new URL('../supabase/migrations/028_premium_trial_and_access.sql',import.meta.url),'utf8');
await db.exec(migration);await db.exec(migration);
await db.exec(await readFile(new URL("../supabase/migrations/027_analytics_v2.sql",import.meta.url),"utf8"));
await db.exec(`create trigger profile_gate before insert or update on profiles for each row execute function enforce_profile_pro_features();`);
const user=async id=>db.query("select set_config('test.user',$1,false)",[id]);
const access=async()=>(await db.query('select account_access() value')).rows[0].value;
await user(old);assert.equal((await access()).has_premium,false);assert.equal((await access()).active_link_limit,1);
await user(young);const youngTrialEnd=(await access()).trial_ends_at;assert.equal((await access()).source,'trial');assert.equal((await access()).days_remaining,27);
await db.query('insert into auth.users(id) values($1)',[fresh]);await user(fresh);
let a=await access();assert.equal(a.source,'trial');assert.equal(a.days_remaining,30);assert.equal(Object.values(a.features).every(Boolean),true);assert.equal(a.active_link_limit,null);
await db.query("insert into profiles(id,theme,background_color) values($1,'neon','preset:black-gold-marble')",[fresh]);
const l1='10000000-0000-0000-0000-000000000001',l2='10000000-0000-0000-0000-000000000002';
await db.query("insert into links(id,profile_id,url,position) values($1,$3,'https://example.com/one',0),($2,$3,'https://example.com/two',1)",[l1,l2,fresh]);
assert.equal((await db.query('select link_is_published($1) ok',[l2])).rows[0].ok,true);
await db.query("update subscriptions set trial_ends_at=now()-interval '1 second' where user_id=$1",[fresh]);
a=await access();assert.equal(a.has_premium,false);assert.equal(a.state,'FREE');
assert.equal((await db.query('select link_is_published($1) ok',[l2])).rows[0].ok,false);
assert.equal((await db.query('select public_link_destination($1) url',[l2])).rows[0].url,null);
assert.equal((await db.query('select record_link_play($1) ok',[l1])).rows[0].ok,false);
const tracked={session:'20000000-0000-0000-0000-000000000001',visitor:'20000000-0000-0000-0000-000000000002',device:'Mobile',browser:'Chrome',os:'Android',source:'Direct',utm:{}};
await db.query('select record_analytics_event($1,$2,$3,$4::jsonb)',[fresh,null,'page_view',JSON.stringify(tracked)]);
await db.query('select record_analytics_event($1,$2,$3,$4::jsonb)',[fresh,l2,'link_click',JSON.stringify(tracked)]);
assert.equal((await db.query('select count(*)::int n from analytics_hourly')).rows[0].n,0);
const analyticStart=new Date(Date.now()-6*86400000).toISOString(),analyticEnd=new Date().toISOString();
assert.equal((await db.query('select analytics_report($1,$2) v',[analyticStart,analyticEnd])).rows[0].v.pro,false);
assert.equal((await db.query('select count(*)::int n from links where active')).rows[0].n,2);
await db.query("insert into profiles(id,theme,background_color,bio) values($1,'neon','preset:black-gold-marble','updated') on conflict(id) do update set bio=excluded.bio",[fresh]);
await assert.rejects(()=>db.query("update profiles set background_color='preset:another' where id=$1",[fresh]));
await db.exec('set role anon');await user(null);
assert.equal((await db.query('select count(*)::int n from links')).rows[0].n,1);await db.exec('reset role');await user(fresh);
await db.exec('set role authenticated');await assert.rejects(()=>db.query("update subscriptions set trial_ends_at=now()+interval '30 days' where user_id=$1",[fresh]));await db.exec('reset role');
assert.equal((await db.query('select begin_premium_checkout($1) v',['monthly'])).rows[0].v.token.length,36);
assert.equal((await db.query('select begin_premium_checkout($1) v',['monthly'])).rows[0].v.busy,true);
const [attempt]=(await db.query('select token from billing_checkout_attempts')).rows;
await db.query('select finish_premium_checkout($1,$2,$3)',[fresh,attempt.token,'https://store.lemonsqueezy.com/checkout/example']);
assert.equal((await db.query('select begin_premium_checkout($1) v',['monthly'])).rows[0].v.url,'https://store.lemonsqueezy.com/checkout/example');
const created=new Date(Date.now()-60000).toISOString();const now=new Date().toISOString();
const snapshot={id:'101',customer_id:'201',variant_id:'301',interval:'monthly',status:'active',provider_status:'active',period_end:new Date(Date.now()+30*86400000).toISOString(),created_at:created,updated_at:now,portal_url:'https://store.lemonsqueezy.com/billing'};
const webhook=async(event,data=snapshot,eventUser=fresh)=>(await db.query('select apply_billing_webhook($1,$2,$3,$4::jsonb) value',[event,'subscription_updated',eventUser,JSON.stringify(data)])).rows[0].value;
assert.equal((await webhook('activation')).applied,true);assert.equal((await access()).source,'subscription');assert.equal((await db.query('select analytics_report($1,$2) v',[analyticStart,analyticEnd])).rows[0].v.pro,true);assert.equal((await webhook('activation')).duplicate,true);
assert.equal((await db.query('select count(*)::int n from billing_checkout_attempts')).rows[0].n,0);
assert.equal((await db.query('select begin_premium_checkout($1) v',['monthly'])).rows[0].v.blocked,true);
assert.equal((await db.query('select claim_pro_welcome() v')).rows[0].v,true);
assert.equal((await db.query('select claim_pro_welcome() v')).rows[0].v,false);
assert.equal((await db.query('select link_is_published($1) ok',[l2])).rows[0].ok,true);
await assert.rejects(()=>webhook('wrong-owner',snapshot,old));
assert.equal((await db.query('select count(*)::int n from billing_webhook_events where id=$1',['wrong-owner'])).rows[0].n,0);
assert.equal((await webhook('stale',{...snapshot,status:'expired',updated_at:created})).stale,true);
assert.equal((await access()).has_premium,true);
await webhook('cancel',{...snapshot,status:'canceled',provider_status:'cancelled',updated_at:new Date(Date.now()+1000).toISOString()});
assert.equal((await access()).state,'PREMIUM_CANCELED');assert.equal((await access()).has_premium,true);
await webhook('past-due',{...snapshot,status:'past_due',provider_status:'past_due',period_end:null,updated_at:new Date(Date.now()+2000).toISOString()});
assert.equal((await access()).state,'PREMIUM_PAST_DUE');assert.equal((await access()).has_premium,true);
await db.query("update subscriptions set past_due_since=now()-interval '15 days' where user_id=$1",[fresh]);assert.equal((await access()).has_premium,false);
await db.query('select refresh_expired_access()');assert.equal((await access()).subscription_status,'expired');
await webhook('renewal',{...snapshot,updated_at:new Date(Date.now()+3000).toISOString()});assert.equal((await access()).has_premium,true);
await webhook('expired',{...snapshot,status:'expired',provider_status:'expired',period_end:new Date(Date.now()-1000).toISOString(),updated_at:new Date(Date.now()+4000).toISOString()});assert.equal((await access()).state,'PREMIUM_EXPIRED');
await webhook('reactivation',{...snapshot,id:'102',created_at:new Date(Date.now()+5000).toISOString(),updated_at:new Date(Date.now()+5000).toISOString()});assert.equal((await access()).has_premium,true);
assert.equal((await webhook('old-subscription',{...snapshot,updated_at:new Date(Date.now()+6000).toISOString()})).stale,true);
await user(young);assert.equal((await access()).trial_ends_at,youngTrialEnd);
await user(null);await assert.rejects(()=>access());
await db.exec('set role authenticated');await assert.rejects(()=>webhook('unauthorized'));await db.exec('reset role');
console.log('Premium SQL: signup trial, remaining trial, all features, timed expiration, Free visibility, preserved content, upgrade gates, paid activation, cancellation, grace, renewal, reactivation, stale/duplicate events, rollback, ownership and checkout deduplication passed.');
} catch(error) { console.error(error.message, error.detail??'', error.hint??'', error.position??'');process.exitCode=1; }
finally { await db.close(); }
