create table if not exists public.account_moderation (
  user_id uuid primary key references auth.users(id) on delete cascade,
  suspended_at timestamptz,
  suspended_by uuid references auth.users(id) on delete set null,
  suspension_reason text check (suspension_reason is null or char_length(suspension_reason) <= 500),
  updated_at timestamptz not null default now()
);

create table if not exists public.profile_reports (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  reporter_id uuid references auth.users(id) on delete set null,
  reason text not null check (reason in ('spam','abuse','impersonation','inappropriate','copyright','other')),
  description text not null default '' check (char_length(description) <= 1000),
  status text not null default 'pending' check (status in ('pending','reviewing','resolved','dismissed')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  resolution_note text check (resolution_note is null or char_length(resolution_note) <= 1000),
  created_at timestamptz not null default now()
);

create index if not exists profile_reports_status_created_idx on public.profile_reports (status, created_at desc);

create table if not exists public.admin_action_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  target_user_id uuid references auth.users(id) on delete set null,
  action text not null check (action in ('suspend_user','reactivate_user','review_report','dismiss_report')),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_action_logs_created_idx on public.admin_action_logs (created_at desc);

create table if not exists public.support_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  email text not null check (char_length(email) between 5 and 320),
  subject text not null check (char_length(subject) between 3 and 120),
  message text not null check (char_length(message) between 10 and 2000),
  status text not null default 'open' check (status in ('open','in_progress','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists support_requests_status_created_idx on public.support_requests (status, created_at desc);

create table if not exists public.link_daily_clicks (
  link_id uuid not null references public.links(id) on delete cascade,
  day date not null default current_date,
  clicks integer not null default 0 check (clicks >= 0),
  primary key (link_id, day)
);

create table if not exists public.request_rate_limits (
  request_key text primary key,
  window_started timestamptz not null default now(),
  hit_count integer not null default 1 check (hit_count > 0)
);

alter table public.account_moderation enable row level security;
alter table public.profile_reports enable row level security;
alter table public.admin_action_logs enable row level security;
alter table public.support_requests enable row level security;
alter table public.link_daily_clicks enable row level security;
alter table public.request_rate_limits enable row level security;

create or replace function public.profile_is_available(target_profile uuid)
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = target_profile and published = true
  ) and not exists (
    select 1 from public.account_moderation
    where user_id = target_profile and suspended_at is not null
  )
$$;

drop policy if exists "Admins view moderation" on public.account_moderation;
create policy "Admins view moderation" on public.account_moderation for select using (public.is_admin());

drop policy if exists "Admins view reports" on public.profile_reports;
create policy "Admins view reports" on public.profile_reports for select using (public.is_admin());
drop policy if exists "Admins update reports" on public.profile_reports;
create policy "Admins update reports" on public.profile_reports for update using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Visitors create reports" on public.profile_reports;
create policy "Visitors create reports" on public.profile_reports for insert with check (
  status = 'pending' and reviewed_by is null and reviewed_at is null
  and (reporter_id is null or reporter_id = auth.uid())
  and public.profile_is_available(profile_id)
);

drop policy if exists "Admins view action logs" on public.admin_action_logs;
create policy "Admins view action logs" on public.admin_action_logs for select using (public.is_admin());

drop policy if exists "Admins view support" on public.support_requests;
create policy "Admins view support" on public.support_requests for select using (public.is_admin());
drop policy if exists "Admins update support" on public.support_requests;
create policy "Admins update support" on public.support_requests for update using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Visitors create support requests" on public.support_requests;
create policy "Visitors create support requests" on public.support_requests for insert with check (
  status = 'open' and (user_id is null or user_id = auth.uid())
);

drop policy if exists "Owners view daily clicks" on public.link_daily_clicks;
create policy "Owners view daily clicks" on public.link_daily_clicks for select using (
  public.is_admin()
  or exists (
    select 1 from public.links
    where links.id = link_daily_clicks.link_id and links.profile_id = auth.uid()
  )
);

create or replace function public.account_is_suspended()
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.account_moderation
    where user_id = auth.uid() and suspended_at is not null
  )
$$;

create or replace function public.check_request_rate_limit(target_key text, max_hits integer, window_seconds integer)
returns boolean language plpgsql security definer set search_path = public
as $$
declare allowed boolean;
begin
  if target_key is null or char_length(target_key) < 16 or max_hits < 1 or window_seconds < 1 then return false; end if;
  insert into public.request_rate_limits (request_key, window_started, hit_count)
  values (target_key, now(), 1)
  on conflict (request_key) do update set
    window_started = case when request_rate_limits.window_started < now() - make_interval(secs => window_seconds) then now() else request_rate_limits.window_started end,
    hit_count = case when request_rate_limits.window_started < now() - make_interval(secs => window_seconds) then 1 else request_rate_limits.hit_count + 1 end
  returning hit_count <= max_hits into allowed;
  return allowed;
end;
$$;

create or replace function public.admin_set_user_suspension(target_user uuid, should_suspend boolean, reason text default null)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Not authorized'; end if;
  if target_user = auth.uid() then raise exception 'Administrators cannot suspend themselves'; end if;
  if should_suspend and (reason is null or char_length(trim(reason)) < 3) then raise exception 'A suspension reason is required'; end if;

  insert into public.account_moderation (user_id, suspended_at, suspended_by, suspension_reason, updated_at)
  values (target_user, case when should_suspend then now() else null end, case when should_suspend then auth.uid() else null end, case when should_suspend then left(trim(reason), 500) else null end, now())
  on conflict (user_id) do update set suspended_at = excluded.suspended_at, suspended_by = excluded.suspended_by,
    suspension_reason = excluded.suspension_reason, updated_at = now();

  insert into public.admin_action_logs (actor_id, target_user_id, action, details)
  values (auth.uid(), target_user, case when should_suspend then 'suspend_user' else 'reactivate_user' end,
    jsonb_build_object('reason', case when should_suspend then left(trim(reason), 500) else null end));
end;
$$;

drop policy if exists "Public profiles are visible" on public.profiles;
create policy "Public profiles are visible" on public.profiles for select using (
  auth.uid() = id or public.is_admin()
  or public.profile_is_available(id)
);

create or replace function public.record_profile_view(target_profile uuid)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if public.profile_is_available(target_profile) then
    insert into public.profile_daily_views (profile_id, day, views)
    values (target_profile, current_date, 1)
    on conflict (profile_id, day) do update set views = profile_daily_views.views + 1;
  end if;
end;
$$;

create or replace function public.public_link_destination(target_link uuid)
returns text language sql stable security definer set search_path = public
as $$
  select links.url from public.links
  where links.id = target_link and links.active = true
    and public.profile_is_available(links.profile_id)
$$;

create or replace function public.record_link_click(target_link uuid)
returns text language plpgsql security definer set search_path = public
as $$
declare destination text;
begin
  update public.links set clicks = clicks + 1
  where id = target_link and active = true and public.profile_is_available(profile_id)
  returning url into destination;

  if destination is not null then
    insert into public.link_daily_clicks (link_id, day, clicks) values (target_link, current_date, 1)
    on conflict (link_id, day) do update set clicks = link_daily_clicks.clicks + 1;
  end if;
  return destination;
end;
$$;

revoke all on function public.account_is_suspended() from public, anon;
revoke all on function public.profile_is_available(uuid) from public;
revoke all on function public.check_request_rate_limit(text, integer, integer) from public, anon, authenticated;
revoke all on function public.admin_set_user_suspension(uuid, boolean, text) from public, anon;
revoke all on function public.record_link_click(uuid) from public, anon, authenticated;
grant execute on function public.account_is_suspended() to authenticated;
grant execute on function public.profile_is_available(uuid) to anon, authenticated, service_role;
grant execute on function public.check_request_rate_limit(text, integer, integer) to service_role;
grant execute on function public.admin_set_user_suspension(uuid, boolean, text) to authenticated;
grant execute on function public.record_link_click(uuid) to service_role;
